mutation UndoReprice2 {
p31: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697181929633", variants: [{id: "gid://shopify/ProductVariant/46914523037857", price: "96.00"}]) { productVariants { id price } userErrors { field message } }
p32: productVariantsBulkUpdate(productId: "gid://shopify/Product/7143847198881", variants: [{id: "gid://shopify/ProductVariant/41270344581281", price: "90.00"}]) { productVariants { id price } userErrors { field message } }
p33: productVariantsBulkUpdate(productId: "gid://shopify/Product/7142282166433", variants: [{id: "gid://shopify/ProductVariant/41267216482465", price: "90.00"}]) { productVariants { id price } userErrors { field message } }
p34: productVariantsBulkUpdate(productId: "gid://shopify/Product/7142285803681", variants: [{id: "gid://shopify/ProductVariant/41267221856417", price: "90.00"}]) { productVariants { id price } userErrors { field message } }
p35: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008144621729", variants: [{id: "gid://shopify/ProductVariant/40916325695649", price: "90.00"}]) { productVariants { id price } userErrors { field message } }
p36: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008162709665", variants: [{id: "gid://shopify/ProductVariant/40916369965217", price: "90.00"}]) { productVariants { id price } userErrors { field message } }
p37: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699190546593", variants: [{id: "gid://shopify/ProductVariant/43015648313505", price: "90.00"}]) { productVariants { id price } userErrors { field message } }
p38: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697182257313", variants: [{id: "gid://shopify/ProductVariant/46914523398305", price: "88.00"}]) { productVariants { id price } userErrors { field message } }
p39: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697182224545", variants: [{id: "gid://shopify/ProductVariant/46914523365537", price: "88.00"}]) { productVariants { id price } userErrors { field message } }
p40: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140465115297", variants: [{id: "gid://shopify/ProductVariant/41262581186721", price: "85.00"}]) { productVariants { id price } userErrors { field message } }
p41: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699194380449", variants: [{id: "gid://shopify/ProductVariant/43015661519009", price: "85.00"}]) { productVariants { id price } userErrors { field message } }
p42: productVariantsBulkUpdate(productId: "gid://shopify/Product/7142330400929", variants: [{id: "gid://shopify/ProductVariant/41267298926753", price: "85.00"}]) { productVariants { id price } userErrors { field message } }
p43: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008138428577", variants: [{id: "gid://shopify/ProductVariant/40916312195233", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p44: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008092684449", variants: [{id: "gid://shopify/ProductVariant/40916161364129", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p45: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008134889633", variants: [{id: "gid://shopify/ProductVariant/40916302561441", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p46: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008065716385", variants: [{id: "gid://shopify/ProductVariant/40916053852321", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p47: productVariantsBulkUpdate(productId: "gid://shopify/Product/7007966986401", variants: [{id: "gid://shopify/ProductVariant/40915656605857", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p48: productVariantsBulkUpdate(productId: "gid://shopify/Product/7007946571937", variants: [{id: "gid://shopify/ProductVariant/40915561742497", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p49: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008097796257", variants: [{id: "gid://shopify/ProductVariant/40916186235041", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p50: productVariantsBulkUpdate(productId: "gid://shopify/Product/7141613830305", variants: [{id: "gid://shopify/ProductVariant/41265264427169", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p51: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008172966049", variants: [{id: "gid://shopify/ProductVariant/40916416168097", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p52: productVariantsBulkUpdate(productId: "gid://shopify/Product/7007963054241", variants: [{id: "gid://shopify/ProductVariant/40915640909985", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p53: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008159793313", variants: [{id: "gid://shopify/ProductVariant/40916365443233", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p54: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008115949729", variants: [{id: "gid://shopify/ProductVariant/40916253311137", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p55: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699213025441", variants: [{id: "gid://shopify/ProductVariant/43015707754657", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p56: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008156876961", variants: [{id: "gid://shopify/ProductVariant/40916360069281", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p57: productVariantsBulkUpdate(productId: "gid://shopify/Product/7007843221665", variants: [{id: "gid://shopify/ProductVariant/40915145425057", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p58: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699219316897", variants: [{id: "gid://shopify/ProductVariant/43015739080865", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p59: productVariantsBulkUpdate(productId: "gid://shopify/Product/7007827853473", variants: [{id: "gid://shopify/ProductVariant/40915090374817", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p60: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008169394337", variants: [{id: "gid://shopify/ProductVariant/40916399587489", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
}
