mutation UndoReprice1 {
p1: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699198509217", variants: [{id: "gid://shopify/ProductVariant/43015678328993", price: "385.00"}]) { productVariants { id price } userErrors { field message } }
p2: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697182126241", variants: [{id: "gid://shopify/ProductVariant/46914523234465", price: "376.00"}]) { productVariants { id price } userErrors { field message } }
p3: productVariantsBulkUpdate(productId: "gid://shopify/Product/7144160952481", variants: [{id: "gid://shopify/ProductVariant/41271141105825", price: "280.00"}]) { productVariants { id price } userErrors { field message } }
p4: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140438999201", variants: [{id: "gid://shopify/ProductVariant/41262530658465", price: "250.00"}]) { productVariants { id price } userErrors { field message } }
p5: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699210109089", variants: [{id: "gid://shopify/ProductVariant/43015701430433", price: "235.00"}]) { productVariants { id price } userErrors { field message } }
p6: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699209355425", variants: [{id: "gid://shopify/ProductVariant/43015699267745", price: "225.00"}]) { productVariants { id price } userErrors { field message } }
p7: productVariantsBulkUpdate(productId: "gid://shopify/Product/7004955213985", variants: [{id: "gid://shopify/ProductVariant/40915020906657", price: "200.00"}]) { productVariants { id price } userErrors { field message } }
p8: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697181798561", variants: [{id: "gid://shopify/ProductVariant/46914522906785", price: "156.00"}]) { productVariants { id price } userErrors { field message } }
p9: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140517773473", variants: [{id: "gid://shopify/ProductVariant/41262702756001", price: "155.00"}]) { productVariants { id price } userErrors { field message } }
p10: productVariantsBulkUpdate(productId: "gid://shopify/Product/7142332498081", variants: [{id: "gid://shopify/ProductVariant/41267304595617", price: "155.00"}]) { productVariants { id price } userErrors { field message } }
p11: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140475338913", variants: [{id: "gid://shopify/ProductVariant/41262600781985", price: "130.00"}]) { productVariants { id price } userErrors { field message } }
p12: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140625776801", variants: [{id: "gid://shopify/ProductVariant/41262878064801", price: "125.00"}]) { productVariants { id price } userErrors { field message } }
p13: productVariantsBulkUpdate(productId: "gid://shopify/Product/7143852605601", variants: [{id: "gid://shopify/ProductVariant/41270356377761", price: "125.00"}]) { productVariants { id price } userErrors { field message } }
p14: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697181831329", variants: [{id: "gid://shopify/ProductVariant/46914522939553", price: "120.00"}]) { productVariants { id price } userErrors { field message } }
p15: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699200082081", variants: [{id: "gid://shopify/ProductVariant/43015680229537", price: "115.00"}]) { productVariants { id price } userErrors { field message } }
p16: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140630134945", variants: [{id: "gid://shopify/ProductVariant/41262885601441", price: "110.00"}]) { productVariants { id price } userErrors { field message } }
p17: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140454662305", variants: [{id: "gid://shopify/ProductVariant/41262561460385", price: "110.00"}]) { productVariants { id price } userErrors { field message } }
p18: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697182027937", variants: [{id: "gid://shopify/ProductVariant/46914523136161", price: "108.00"}]) { productVariants { id price } userErrors { field message } }
p19: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697181864097", variants: [{id: "gid://shopify/ProductVariant/46914522972321", price: "108.00"}]) { productVariants { id price } userErrors { field message } }
p20: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008071745697", variants: [{id: "gid://shopify/ProductVariant/40916074987681", price: "100.00"}]) { productVariants { id price } userErrors { field message } }
p21: productVariantsBulkUpdate(productId: "gid://shopify/Product/7144441577633", variants: [{id: "gid://shopify/ProductVariant/41271656710305", price: "100.00"}]) { productVariants { id price } userErrors { field message } }
p22: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140492214433", variants: [{id: "gid://shopify/ProductVariant/41262640824481", price: "100.00"}]) { productVariants { id price } userErrors { field message } }
p23: productVariantsBulkUpdate(productId: "gid://shopify/Product/7143892615329", variants: [{id: "gid://shopify/ProductVariant/41270437052577", price: "100.00"}]) { productVariants { id price } userErrors { field message } }
p24: productVariantsBulkUpdate(productId: "gid://shopify/Product/7144435581089", variants: [{id: "gid://shopify/ProductVariant/41271648157857", price: "100.00"}]) { productVariants { id price } userErrors { field message } }
p25: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140450795681", variants: [{id: "gid://shopify/ProductVariant/41262548254881", price: "100.00"}]) { productVariants { id price } userErrors { field message } }
p26: productVariantsBulkUpdate(productId: "gid://shopify/Product/7700340900001", variants: [{id: "gid://shopify/ProductVariant/43019705974945", price: "100.00"}]) { productVariants { id price } userErrors { field message } }
p27: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140621779105", variants: [{id: "gid://shopify/ProductVariant/41262871642273", price: "100.00"}]) { productVariants { id price } userErrors { field message } }
p28: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008150487201", variants: [{id: "gid://shopify/ProductVariant/40916342145185", price: "100.00"}]) { productVariants { id price } userErrors { field message } }
p29: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697182060705", variants: [{id: "gid://shopify/ProductVariant/46914523168929", price: "96.00"}]) { productVariants { id price } userErrors { field message } }
p30: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697181962401", variants: [{id: "gid://shopify/ProductVariant/46914523070625", price: "96.00"}]) { productVariants { id price } userErrors { field message } }
}
