mutation UndoReprice3 {
p61: productVariantsBulkUpdate(productId: "gid://shopify/Product/7007956795553", variants: [{id: "gid://shopify/ProductVariant/40915605815457", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p62: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140634099873", variants: [{id: "gid://shopify/ProductVariant/41262893072545", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p63: productVariantsBulkUpdate(productId: "gid://shopify/Product/7008166019233", variants: [{id: "gid://shopify/ProductVariant/40916384088225", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p64: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697182191777", variants: [{id: "gid://shopify/ProductVariant/46914523300001", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p65: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697181995169", variants: [{id: "gid://shopify/ProductVariant/46914523103393", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p66: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697181896865", variants: [{id: "gid://shopify/ProductVariant/46914523005089", price: "80.00"}]) { productVariants { id price } userErrors { field message } }
p67: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140527014049", variants: [{id: "gid://shopify/ProductVariant/41262727332001", price: "75.00"}]) { productVariants { id price } userErrors { field message } }
p68: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140461019297", variants: [{id: "gid://shopify/ProductVariant/41262572667041", price: "75.00"}]) { productVariants { id price } userErrors { field message } }
p69: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699192545441", variants: [{id: "gid://shopify/ProductVariant/43015657029793", price: "75.00"}]) { productVariants { id price } userErrors { field message } }
p70: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699194675361", variants: [{id: "gid://shopify/ProductVariant/43015663517857", price: "75.00"}]) { productVariants { id price } userErrors { field message } }
p71: productVariantsBulkUpdate(productId: "gid://shopify/Product/7142340165793", variants: [{id: "gid://shopify/ProductVariant/41267325567137", price: "75.00"}]) { productVariants { id price } userErrors { field message } }
p72: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699192971425", variants: [{id: "gid://shopify/ProductVariant/43015657816225", price: "75.00"}]) { productVariants { id price } userErrors { field message } }
p73: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140487332001", variants: [{id: "gid://shopify/ProductVariant/41262630600865", price: "70.00"}]) { productVariants { id price } userErrors { field message } }
p74: productVariantsBulkUpdate(productId: "gid://shopify/Product/7143839301793", variants: [{id: "gid://shopify/ProductVariant/41270321217697", price: "70.00"}]) { productVariants { id price } userErrors { field message } }
p75: productVariantsBulkUpdate(productId: "gid://shopify/Product/7142325321889", variants: [{id: "gid://shopify/ProductVariant/41267286737057", price: "70.00"}]) { productVariants { id price } userErrors { field message } }
p76: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699217285281", variants: [{id: "gid://shopify/ProductVariant/43015727939745", price: "70.00"}]) { productVariants { id price } userErrors { field message } }
p77: productVariantsBulkUpdate(productId: "gid://shopify/Product/7142269321377", variants: [{id: "gid://shopify/ProductVariant/41267186827425", price: "70.00"}]) { productVariants { id price } userErrors { field message } }
p78: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699224297633", variants: [{id: "gid://shopify/ProductVariant/43015757988001", price: "70.00"}]) { productVariants { id price } userErrors { field message } }
p79: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699205816481", variants: [{id: "gid://shopify/ProductVariant/43015691174049", price: "70.00"}]) { productVariants { id price } userErrors { field message } }
p80: productVariantsBulkUpdate(productId: "gid://shopify/Product/7144157511841", variants: [{id: "gid://shopify/ProductVariant/41271131766945", price: "65.00"}]) { productVariants { id price } userErrors { field message } }
p81: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140532388001", variants: [{id: "gid://shopify/ProductVariant/41262738931873", price: "60.00"}]) { productVariants { id price } userErrors { field message } }
p82: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140482220193", variants: [{id: "gid://shopify/ProductVariant/41262615855265", price: "60.00"}]) { productVariants { id price } userErrors { field message } }
p83: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140469178529", variants: [{id: "gid://shopify/ProductVariant/41262590132385", price: "60.00"}]) { productVariants { id price } userErrors { field message } }
p84: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697182093473", variants: [{id: "gid://shopify/ProductVariant/46914523201697", price: "60.00"}]) { productVariants { id price } userErrors { field message } }
p85: productVariantsBulkUpdate(productId: "gid://shopify/Product/7699188973729", variants: [{id: "gid://shopify/ProductVariant/43015641530529", price: "50.00"}]) { productVariants { id price } userErrors { field message } }
p86: productVariantsBulkUpdate(productId: "gid://shopify/Product/7140522983585", variants: [{id: "gid://shopify/ProductVariant/41262715699361", price: "50.00"}]) { productVariants { id price } userErrors { field message } }
p87: productVariantsBulkUpdate(productId: "gid://shopify/Product/8697181765793", variants: [{id: "gid://shopify/ProductVariant/46914522874017", price: "48.00"}]) { productVariants { id price } userErrors { field message } }
p88: productVariantsBulkUpdate(productId: "gid://shopify/Product/7144448000161", variants: [{id: "gid://shopify/ProductVariant/41271672766625", price: "15.00"}]) { productVariants { id price } userErrors { field message } }
}
